language: php

php:
  - 5.5

before_script:
  - composer self-update
  - composer update --prefer-source

script:
  - ./vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v

notifications:
  irc: "irc.freenode.org#pmg"
  email: false
