language: php

php:
  - 5.5
  - 5.6

before_script:
  - composer self-update
  - composer install

script:
  - ./vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml
  - ./vendor/bin/phpcs --standard=PSR2 --ignore=./src/MCNElasticSearch/Listener/AbstractDoctrineORMSynchronizer.php ./src/

after_script:
  - php vendor/bin/coveralls -v

notifications:
  irc: "irc.freenode.org#pmg.se"
  email: false
